project_id = "jexrtsyokhegjxnvqjur"

[functions.aggregate-leaderboard]
verify_jwt = false

[functions.cleanup-old-notifications]
verify_jwt = false

[functions.send-referral-notification]
verify_jwt = false


[functions.yookassa-create-payment]
verify_jwt = false

[functions.yookassa-webhook]
verify_jwt = false
